# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903b6e14ad7bfb4748b9c8c8a00a8b404d130186d57ec1ce038c5a5954595a017c325586a94773281e5b78a35be24b33b31b7bf0803938ecc1e7692f797b5319

test:
  secret_key_base: bb95744d8bcf144444213440311dd1b701199c49b05c81f575a3e788e53fef3c2d3feafd744b61cec955acca154d8ce8a843e8f24445c3c9b50ab7d235bdfc0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
